# Generated by Django 3.1 on 2020-09-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads_feed',
            old_name='name',
            new_name='ad_genre',
        ),
        migrations.RenameField(
            model_name='ads_feed',
            old_name='title',
            new_name='ad_links',
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='ad_channel_link',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='ad_cta_link',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='ad_description',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='ad_dislikes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='ad_likes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='ad_title',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='ad_unlisted',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='ad_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='channel_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='creation_date',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='length',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='orgv_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='subscribers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='total_videos',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='upload_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ads_feed',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
    ]
